### ISSUE TITLE
Convert to python 3?

### ISSUE THREAD

**Issue by windowshopr** [Malemm/ml-graphology#1]
Would love to see this converted to Python 3, and maybe the list of images used in the initial training? I've updated all the "print"s in the code, but I receive errors that I'm not sure how to fix depending on the images I use, from:

mean_angle = angle_sum / countour_count
ZeroDivisionError: float division by zero

...to

TypeError: slice indices must be integers or None or have an __index__ method

Are there certain types of images that work better? Thanks!

**Comment by windowshopr** [comment]
UPDATE:

I've updated to Python 3, but receive the:

TypeError: slice indices must be integers or None or have an index method

...error when trying to run extract_routine.py. Thoughts?

**Comment by Yashg2910** [comment]
Even i am facing same problem. Consider me as a newbie in machine learning. Can you let us know how to run it over python 3?
Or if not, all the requirements for the project.

**Comment by titanh3art** [comment]
@windowshopr 
```
mean_angle = angle_sum / countour_count
ZeroDivisionError: float division by zero
```
is because the `countour_count` is zero in your image. `contour_count` is the number of contours, i.e. blocks of lines or individual lines in the image. For example, it may happen if your image is completely empty. It may also happen if the number of vertical pixels/height in pixels for all the contours is less than 20 (hard coded arbitrary value based on my dataset in line number 80 as follows).
```
if h>w or h<20:
    continue
```
This condition is added to filter out unwanted contours in the image which are not actually handwriting lines. You should get an idea of the smallest height of all the handwriting in your dataset and set the value. Instead of writing like 20, you could put a global constant like `MINIMUM_HANDWRITING_HEIGHT = 20`  use it instead. You have to find your suitable constant according to your dataset.

`TypeError: slice indices must be integers or None or have an index method` may be due to different version of opencv or numpy since you are running on Python 3. If you could provide the exact lines where these errors occurred, I may be able to look into it.

@Yashg2910  @windowshopr when you convert to python 3, be aware of differences between the opencv, numpy, scikit learn or any other library functions of different python versions.

**Comment by titanh3art** [comment]
Here is the link to the dataset that I used.
http://www.fki.inf.unibe.ch/databases/iam-handwriting-database
PS. Don't use directly. Get rid of the printed texts and scale all the images to a specific resolution (width).

**Comment by titanh3art** [comment]
@Yashg2910  @windowshopr I have uploaded my project thesis. I hope you find it helpful.

**Comment by windowshopr** [comment]
Thanks for your help @Malemm ! This helps a lot. Can't wait to play with it again!

**Comment by Yashg2910** [comment]
Thanks a lot for helping out with this! and

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by windowshopr** [comment]
One thing I'm noticing is it has a hard time with multi-line images. 
![1](https://user-images.githubusercontent.com/40477419/53616897-6797ee00-3baa-11e9-81c7-73180fc3f707.jpg)
![2](https://user-images.githubusercontent.com/40477419/53616898-6797ee00-3baa-11e9-9cb4-6181f34d4547.jpg)

I made a binary coloured sample of handwriting, one line, and multi-line. When I run the train_predict.py on the single line file, it works well, but when I try it on the multi-line sample, I receive:

Enter file name to predict or z to exit: 2.jpg
Traceback (most recent call last):
  File "train_predict.py", line 173, in <module>
    raw_features = extract.start(file_name)
  File "C:\Users\windowshopr\Desktop\Python Scripts\Graphology\ml-graphology (issue opened)\extract.py", line 768, in start
    lineIndices = extractLines(straightened)
  File "C:\Users\windowshopr\Desktop\Python Scripts\Graphology\ml-graphology (issue opened)\extract.py", line 339, in extractLines
    segment = hpList[line[0]:line[1]]
TypeError: slice indices must be integers or None or have an __index__ method

Any ideas on this issue @Malemm ? Thanks again! Love the program.

**Comment by titanh3art** [comment]
@windowshopr I appreciate your love for the project.
The error may be because it is not finding any handwriting lines in the image and so `fineLines` from which `line[0]` and `line[1]` are enumerated is empty list.

Yes the algorithm will have a hard time on handwriting with extremely crowded lines. In those cases, it is very difficult to find the arbitrary `ANCHOR_POINT` value. There are commented out sections of displaying the extracted lines. Try to see the extracted lines using them and see if lines are being extracted properly. Also try to find a suitable `ANCHOR_POINT` for you images after setting them at a specific width of resolution. It's important. It is the sum of all the pixel values (gray levels) of a row (imagine your image as a 2D matrix of rows and columns). It is used to constitute if a particular row is part of a handwriting line or is part of the empty space between lines.

**Comment by windowshopr** [comment]
@Malemm Thanks again for your help! I'll play with the width of resolution and see what I can do. Thanks again! Love the work
